### ISSUE TITLE
"self.data.update & self.only_direct" in update

### ISSUE THREAD

**Issue by DuckY1987** [kennell/schiene#19] opened 2019-02-19 14:36 UTC
i use this package with home-assistant.

Since i upgraded i have following error:

"/usr/local/lib/python3.5/dist-packages/homeassistant/components/sensor/deutsche_bahn.py", line 82, in update
"/usr/local/lib/python3.5/dist-packages/homeassistant/components/sensor/deutsche_bahn.py", line 105, in update

Here is the same error reported what i had a couple times in log:

https://github.com/home-assistant/home-assistant/issues/21118

self.data.update self.only_direct

Could you please fix it? :-)

Thanks a lot!

**Comment by kennell** [comment] 2019-02-19 17:42
Duplicate of #18

**Closed by kennell** 2019-02-19 17:42 UTC

**Comment by kennell** [comment] 2019-03-08 09:31
FYI: Fixed in https://github.com/kennell/schiene/pull/20, released on PyPI as version `0.23`
